version: '2'
services:
  cbwp-auto-switch:    
    build: 
      context: .
      dockerfile: "deploy/docker/Dockerfile"
    restart: "no"
    volumes:    
    - ./config.yaml:/src/github.com/zeusro/common-bandwidth-auto-switch/config.yaml:ro